# Generated by Django 4.0.4 on 2022-05-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commant',
            new_name='comment',
        ),
    ]
